// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Produced by backend/scripts/generate_frontend_tables.py from the Python
// tables in backend/app/utils/bluebook_patterns.py, which are the source of
// truth. Regenerate with:
//
//     cd backend && python scripts/generate_frontend_tables.py
//
// A backend test fails if this file is out of date.

export const PARTY_ABBREVIATIONS = {
  "Administration": "Admin.",
  "Administrative": "Admin.",
  "Administrator": "Adm'r",
  "Administratrix": "Adm'x",
  "America": "Am.",
  "American": "Am.",
  "Association": "Ass'n",
  "Atlantic": "Atl.",
  "Authority": "Auth.",
  "Automobile": "Auto.",
  "Automotive": "Auto.",
  "Avenue": "Ave.",
  "Board": "Bd.",
  "Brotherhood": "Bhd.",
  "Brothers": "Bros.",
  "Building": "Bldg.",
  "Center": "Ctr.",
  "Central": "Cent.",
  "Chemical": "Chem.",
  "Commission": "Comm'n",
  "Commissioner": "Comm'r",
  "Committee": "Comm.",
  "Communication": "Commc'n",
  "Communications": "Commc'ns",
  "Community": "Cmty.",
  "Company": "Co.",
  "Consolidated": "Consol.",
  "Construction": "Constr.",
  "Corporation": "Corp.",
  "County": "Cnty.",
  "Department": "Dep't",
  "Development": "Dev.",
  "Director": "Dir.",
  "Distributor": "Distrib.",
  "Distributors": "Distribs.",
  "District": "Dist.",
  "Division": "Div.",
  "East": "E.",
  "Eastern": "E.",
  "Economic": "Econ.",
  "Education": "Educ.",
  "Educational": "Educ.",
  "Electric": "Elec.",
  "Electrical": "Elec.",
  "Electronic": "Elec.",
  "Electronics": "Elecs.",
  "Engineering": "Eng'g",
  "Enterprise": "Enter.",
  "Enterprises": "Enters.",
  "Entertainment": "Ent.",
  "Environment": "Env't",
  "Environmental": "Envtl.",
  "Equipment": "Equip.",
  "Exchange": "Exch.",
  "Executor": "Ex'r",
  "Executrix": "Ex'x",
  "Export": "Exp.",
  "Federal": "Fed.",
  "Federation": "Fed'n",
  "Financial": "Fin.",
  "Foundation": "Found.",
  "General": "Gen.",
  "Government": "Gov't",
  "Guaranty": "Guar.",
  "Hospital": "Hosp.",
  "Housing": "Hous.",
  "Import": "Imp.",
  "Incorporated": "Inc.",
  "Indemnity": "Indem.",
  "Independent": "Indep.",
  "Industrial": "Indus.",
  "Industries": "Indus.",
  "Industry": "Indus.",
  "Information": "Info.",
  "Institute": "Inst.",
  "Institution": "Inst.",
  "Insurance": "Ins.",
  "International": "Int'l",
  "Investment": "Inv.",
  "Investor": "Inv.",
  "Laboratories": "Labs.",
  "Laboratory": "Lab.",
  "Liability": "Liab.",
  "Limited": "Ltd.",
  "Litigation": "Litig.",
  "Machine": "Mach.",
  "Machinery": "Mach.",
  "Maintenance": "Maint.",
  "Management": "Mgmt.",
  "Manager": "Mgr.",
  "Manufacturer": "Mfr.",
  "Manufacturers": "Mfrs.",
  "Manufacturing": "Mfg.",
  "Market": "Mkt.",
  "Marketing": "Mktg.",
  "Mechanical": "Mech.",
  "Medical": "Med.",
  "Memorial": "Mem'l",
  "Merchant": "Merch.",
  "Metropolitan": "Metro.",
  "Municipal": "Mun.",
  "Mutual": "Mut.",
  "National": "Nat'l",
  "North": "N.",
  "Northeast": "Ne.",
  "Northern": "N.",
  "Northwest": "Nw.",
  "Number": "No.",
  "Organization": "Org.",
  "Pacific": "Pac.",
  "Partnership": "P'ship",
  "Petroleum": "Pet.",
  "Pharmaceutical": "Pharm.",
  "President": "Pres.",
  "Product": "Prod.",
  "Production": "Prod.",
  "Products": "Prods.",
  "Professional": "Prof'l",
  "Property": "Prop.",
  "Protection": "Prot.",
  "Public": "Pub.",
  "Publication": "Publ'n",
  "Publications": "Publ'ns",
  "Publishing": "Publ'g",
  "Railroad": "R.R.",
  "Railway": "Ry.",
  "Regional": "Reg'l",
  "Reproduction": "Reprod.",
  "Research": "Rsch.",
  "Resource": "Res.",
  "Resources": "Res.",
  "Restaurant": "Rest.",
  "Road": "Rd.",
  "Savings": "Sav.",
  "School": "Sch.",
  "Science": "Sci.",
  "Scientific": "Sci.",
  "Secretary": "Sec'y",
  "Security": "Sec.",
  "Service": "Serv.",
  "Services": "Servs.",
  "Society": "Soc'y",
  "South": "S.",
  "Southeast": "Se.",
  "Southern": "S.",
  "Southwest": "Sw.",
  "Standard": "Stand.",
  "State": "State",
  "Steamship": "S.S.",
  "Street": "St.",
  "Subcommittee": "Subcomm.",
  "Superintendent": "Supt.",
  "Surety": "Sur.",
  "System": "Sys.",
  "Systems": "Sys.",
  "Technical": "Tech.",
  "Technology": "Tech.",
  "Telecommunications": "Telecomms.",
  "Telephone": "Tel.",
  "Television": "T.V.",
  "Temporary": "Temp.",
  "Textile": "Textile",
  "Transcontinental": "Transcon.",
  "Transport": "Transp.",
  "Transportation": "Transp.",
  "Trustee": "Tr.",
  "Uniform": "Unif.",
  "United": "United",
  "United States": "United States",
  "University": "Univ.",
  "Utilities": "Utils.",
  "Utility": "Util.",
  "Village": "Vill.",
  "West": "W.",
  "Western": "W.",
  "and": "&"
};

export const STATE_ABBREVIATIONS = {
  "Alabama": "Ala.",
  "Alaska": "Alaska",
  "Arizona": "Ariz.",
  "Arkansas": "Ark.",
  "California": "Cal.",
  "Colorado": "Colo.",
  "Connecticut": "Conn.",
  "Delaware": "Del.",
  "District of Columbia": "D.C.",
  "Florida": "Fla.",
  "Georgia": "Ga.",
  "Hawaii": "Haw.",
  "Idaho": "Idaho",
  "Illinois": "Ill.",
  "Indiana": "Ind.",
  "Iowa": "Iowa",
  "Kansas": "Kan.",
  "Kentucky": "Ky.",
  "Louisiana": "La.",
  "Maine": "Me.",
  "Maryland": "Md.",
  "Massachusetts": "Mass.",
  "Michigan": "Mich.",
  "Minnesota": "Minn.",
  "Mississippi": "Miss.",
  "Missouri": "Mo.",
  "Montana": "Mont.",
  "Nebraska": "Neb.",
  "Nevada": "Nev.",
  "New Hampshire": "N.H.",
  "New Jersey": "N.J.",
  "New Mexico": "N.M.",
  "New York": "N.Y.",
  "North Carolina": "N.C.",
  "North Dakota": "N.D.",
  "Ohio": "Ohio",
  "Oklahoma": "Okla.",
  "Oregon": "Or.",
  "Pennsylvania": "Pa.",
  "Rhode Island": "R.I.",
  "South Carolina": "S.C.",
  "South Dakota": "S.D.",
  "Tennessee": "Tenn.",
  "Texas": "Tex.",
  "Utah": "Utah",
  "Vermont": "Vt.",
  "Virginia": "Va.",
  "Washington": "Wash.",
  "West Virginia": "W. Va.",
  "Wisconsin": "Wis.",
  "Wyoming": "Wyo."
};

export const REPORTER_ABBREVIATIONS = {
  "Atlantic Reporter": "A.",
  "Atlantic Reporter Second Series": "A.2d",
  "Atlantic Reporter Third Series": "A.3d",
  "Bankruptcy Reporter": "B.R.",
  "California Reporter": "Cal. Rptr.",
  "California Reporter Second Series": "Cal. Rptr. 2d",
  "California Reporter Third Series": "Cal. Rptr. 3d",
  "Federal Claims Reporter": "Fed. Cl.",
  "Federal Reporter": "F.",
  "Federal Reporter Fourth Series": "F.4d",
  "Federal Reporter Second Series": "F.2d",
  "Federal Reporter Third Series": "F.3d",
  "Federal Rules Decisions": "F.R.D.",
  "Federal Supplement": "F. Supp.",
  "Federal Supplement Second Series": "F. Supp. 2d",
  "Federal Supplement Third Series": "F. Supp. 3d",
  "Lawyers Edition": "L. Ed.",
  "Lawyers Edition Second": "L. Ed. 2d",
  "Military Justice Reporter": "M.J.",
  "New York Supplement": "N.Y.S.",
  "New York Supplement Second Series": "N.Y.S.2d",
  "New York Supplement Third Series": "N.Y.S.3d",
  "North Eastern Reporter": "N.E.",
  "North Eastern Reporter Second Series": "N.E.2d",
  "North Eastern Reporter Third Series": "N.E.3d",
  "North Western Reporter": "N.W.",
  "North Western Reporter Second Series": "N.W.2d",
  "Pacific Reporter": "P.",
  "Pacific Reporter Second Series": "P.2d",
  "Pacific Reporter Third Series": "P.3d",
  "South Eastern Reporter": "S.E.",
  "South Eastern Reporter Second Series": "S.E.2d",
  "South Western Reporter": "S.W.",
  "South Western Reporter Second Series": "S.W.2d",
  "South Western Reporter Third Series": "S.W.3d",
  "Southern Reporter": "So.",
  "Southern Reporter Second Series": "So. 2d",
  "Southern Reporter Third Series": "So. 3d",
  "Supreme Court Reporter": "S. Ct.",
  "United States Reports": "U.S.",
  "Veterans Appeals Reporter": "Vet. App."
};

export const COURT_ABBREVIATIONS = {
  "Central District of California": "C.D. Cal.",
  "D.C. Circuit": "D.C. Cir.",
  "District of Columbia": "D.D.C.",
  "District of Delaware": "D. Del.",
  "District of Massachusetts": "D. Mass.",
  "Eastern District of New York": "E.D.N.Y.",
  "Eastern District of Pennsylvania": "E.D. Pa.",
  "Eastern District of Virginia": "E.D. Va.",
  "Eighth Circuit": "8th Cir.",
  "Eleventh Circuit": "11th Cir.",
  "Federal Circuit": "Fed. Cir.",
  "Fifth Circuit": "5th Cir.",
  "First Circuit": "1st Cir.",
  "Fourth Circuit": "4th Cir.",
  "Ninth Circuit": "9th Cir.",
  "Northern District of California": "N.D. Cal.",
  "Northern District of Illinois": "N.D. Ill.",
  "Second Circuit": "2d Cir.",
  "Seventh Circuit": "7th Cir.",
  "Sixth Circuit": "6th Cir.",
  "Southern District of New York": "S.D.N.Y.",
  "Supreme Court": "",
  "Supreme Court of the United States": "",
  "Tenth Circuit": "10th Cir.",
  "Third Circuit": "3d Cir.",
  "United States Court of Appeals for the District of Columbia Circuit": "D.C. Cir.",
  "United States Court of Appeals for the Eighth Circuit": "8th Cir.",
  "United States Court of Appeals for the Eleventh Circuit": "11th Cir.",
  "United States Court of Appeals for the Federal Circuit": "Fed. Cir.",
  "United States Court of Appeals for the Fifth Circuit": "5th Cir.",
  "United States Court of Appeals for the First Circuit": "1st Cir.",
  "United States Court of Appeals for the Fourth Circuit": "4th Cir.",
  "United States Court of Appeals for the Ninth Circuit": "9th Cir.",
  "United States Court of Appeals for the Second Circuit": "2d Cir.",
  "United States Court of Appeals for the Seventh Circuit": "7th Cir.",
  "United States Court of Appeals for the Sixth Circuit": "6th Cir.",
  "United States Court of Appeals for the Tenth Circuit": "10th Cir.",
  "United States Court of Appeals for the Third Circuit": "3d Cir."
};

export const FIELD_GUIDANCE = {
  "author": {
    "label": "author",
    "rule": "Rule 15.1",
    "why": "The full name of the author, as it appears on the publication."
  },
  "code": {
    "label": "code",
    "rule": "Rule 12.3",
    "why": "The code being cited, usually U.S.C."
  },
  "court": {
    "label": "court",
    "rule": "Rule 10.4",
    "why": "The deciding court, in the parenthetical. Omitted for the U.S. Supreme Court."
  },
  "journal": {
    "label": "journal",
    "rule": "Rule 16.4",
    "why": "The abbreviated periodical name. See Table 13."
  },
  "page": {
    "label": "first page",
    "rule": "Rule 10.3.2",
    "why": "The page the opinion begins on, not the page you are quoting."
  },
  "parties": {
    "label": "party names",
    "rule": "Rule 10.2",
    "why": "The first-listed party on each side, separated by “v.”"
  },
  "reporter": {
    "label": "reporter",
    "rule": "Rule 10.3.2",
    "why": "The abbreviated reporter, for example U.S., S. Ct. or F.4th. See Table 1."
  },
  "section": {
    "label": "section",
    "rule": "Rule 12.3",
    "why": "The section number, after the § symbol."
  },
  "title": {
    "label": "title",
    "rule": "Rule 15.3",
    "why": "The full title of the work."
  },
  "title_number": {
    "label": "title number",
    "rule": "Rule 12.3",
    "why": "The code title, the number before U.S.C."
  },
  "url": {
    "label": "URL",
    "rule": "Rule 18.2",
    "why": "The direct address of the source."
  },
  "volume": {
    "label": "volume number",
    "rule": "Rule 10.3.2",
    "why": "The reporter volume the case starts in, before the reporter name."
  },
  "year": {
    "label": "year",
    "rule": "Rule 10.5",
    "why": "The year of decision, in the same parenthetical as the court."
  }
};

export const CITATION_TEMPLATES = {
  "book": "{author}, {title} ({year}).",
  "case": "*{parties}*, {volume} {reporter} {page} ({court}{year}).",
  "law_review": "{author}, *{title}*, {volume} {journal} {page} ({year}).",
  "regulation": "{title_number} {code} § {section}.",
  "statute": "{title_number} {code} § {section}.",
  "website": "{author}, *{title}*, {url}."
};
